### ISSUE TITLE
Incompatibility with Redis 3.2

### ISSUE THREAD

**Issue by bcorijn** [Janpot/fantastiq#2]
When using fantastiq backed by a Redis instance of version `3.2.6`, there seems to be an abnormally high CPU usage in idle state (at least a x20 of what we would expect) and when trying to add items to the queue, the following error is seen: 
```
ERR Error running script (call to f_ef853f0b10765c11b5e519082d28f6e2bf6368dc): @/var/www/node_modules/fantastiq/lib/lua/fantastiq.lua:110: @user_script: 110: Lua redis() command arguments must be strings or integers
```
Running with Redis 2.8 behaves as expected.

**Comment by bcorijn** [comment]
Upon further inspection, the high idle CPU usage is also present on Redis `2.8`. Main problem with `3.x` is not being able to add items to the queue.  Will open a separate ticket related to idle CPU usage.

**Comment by Janpot** [comment]
closed by https://github.com/Janpot/fantastiq/commit/09a84edcf19ab207e95b69ca37be395afe2f93d9
